server:
  port: 9090

spring:
    datasource:
        url:
        username: 
        password: 
        driver-class-name: 

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                showsql: ture
                formatsql: ture